### ISSUE TITLE
Additional dependencies info

### ISSUE THREAD

**Issue by egalyaev** [rditech/rdi-live#6]
Dear David,
Could you please include the info on additional required dependencies that are needed (by rdi-live/live) and implied but not included. Perhaps what has to be in the $GOPATH for it to build.
Any help and clarification is appreciated! Alternatively some added guidance in the instruction / documentation that covers that (lists the prerequisites from clean slate) in a reasonably comprehensive way would be great.
Evgeny.

**Comment by decibelcooper** [comment]
Hello Eugene,

The README states basic installation instructions.  While basic, these are complete.  The single stated prerequisite is go 1.11 or newer.  If my memory serves me correctly, "modules" were supported automatically for out-of-gopath builds starting from go 1.11.  All dependencies are stated idiomatically using the go module framework, and are automatically collected by the go toolchain in the command stated in the README:
```shell
go get github.com/rditech/rdi-live/tools/...
```

Upon successful completion of the above command, all of the tool binaries, including `rdi-live`, are placed in your `$GOPATH/bin`.  If you need to modify the code, I recommend working with the repo outside of your gopath, and building the binaries with
```shell
go install ./tools/...
```
when in the root repo directory.  All of this is completely go-idiomatic, and extra documentation of dependencies would only be superfluous.  You can, however, take a look at the [go.mod](https://github.com/rditech/rdi-live/blob/master/go.mod) file to see particular dependencies in the go modules format.  A word to the wise: be careful updating `go.mod`, since breaking changes can occur.

**Comment by egalyaev** [comment]
Gotcha, much appreciated.
Will try to move fwd...

Best,
Eugene.
